-- Create waitlist table
CREATE TABLE IF NOT EXISTS public.waitlist (
  id bigint generated by default as identity not null,
  email text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint waitlist_pkey primary key (id),
  constraint waitlist_email_key unique (email)
);

-- Enable RLS
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

-- Allow anonymous and authenticated inserts
-- Using explicit roles can prevent unexpected failures in certain client configurations
DROP POLICY IF EXISTS "Enable insert for everyone" ON public.waitlist;
CREATE POLICY "Enable insert for everyone" ON public.waitlist
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- Allow users to see if they are already on the waitlist (based on email)
-- This prevents the "new row violates RLS" error when the client tries to return the inserted row
CREATE POLICY "Enable select for everyone" ON public.waitlist
  FOR SELECT
  TO anon, authenticated
  USING (true);
